---
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-24.04
    environment: release
    if: github.repository_owner == 'voxpupuli'

    # required permissionss to make a GitHub release and push to the GitHub Gem Registry
    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - uses: voxpupuli/ruby-release@v0
      - name: Setup GitHub packages access
        run: |
          mkdir -p ~/.gem
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
      - name: Publish gem to GitHub packages
        run: gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
      - name: Create Release Page
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} --generate-notes
      - name: Attach gem to GitHub Release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} *.gem
